In [2]:
import pandas as pd
import numpy as np

# Dataset1 and Dataset2 EDA

In [3]:
dataset1 = pd.read_csv("/root/deep-mutational-scan-evalation/Processed_K50_dG_datasets/K50_dG_Dataset1_Dataset2.csv")

/opt/anaconda3/envs/openfold_venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3257: DtypeWarning: Columns (30,36) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
dataset1.columns

Index(['name', 'dna_seq', 'log10_K50_t', 'log10_K50_t_95CI_high',
       'log10_K50_t_95CI_low', 'log10_K50_t_95CI', 'fitting_error_t',
       'log10_K50unfolded_t', 'deltaG_t', 'deltaG_t_95CI_high',
       'deltaG_t_95CI_low', 'deltaG_t_95CI', 'log10_K50_c',
       'log10_K50_c_95CI_high', 'log10_K50_c_95CI_low', 'log10_K50_c_95CI',
       'fitting_error_c', 'log10_K50unfolded_c', 'deltaG_c',
       'deltaG_c_95CI_high', 'deltaG_c_95CI_low', 'deltaG_c_95CI', 'deltaG',
       'deltaG_95CI_high', 'deltaG_95CI_low', 'deltaG_95CI', 'aa_seq_full',
       'aa_seq', 'mut_type', 'WT_name', 'WT_cluster', 'log10_K50_trypsin_ML',
       'log10_K50_chymotrypsin_ML', 'dG_ML', 'ddG_ML', 'Stabilizing_mut',
       'match_aaseq', 'name_original'],
      dtype='object')

In [5]:
dataset1.loc[:, ["name", "aa_seq", "mut_type", "WT_name", "WT_cluster", "name_original"]].head(10)

,name,aa_seq,mut_type,WT_name,WT_cluster,name_original
0,1GYZ.pdb,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb
1,1GYZ.pdb,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb
2,1GYZ.pdb_wtm,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wtm
3,1GYZ.pdb_wte,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wte
4,1GYZ.pdb_wty,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wty
5,1GYZ.pdb_wth,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wth
6,1GYZ.pdb_W1Q,QIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1Q,1GYZ.pdb,100,1GYZ.pdb_W1Q
7,1GYZ.pdb_W1E,EIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1E,1GYZ.pdb,100,1GYZ.pdb_W1E
8,1GYZ.pdb_W1N,NIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1N,1GYZ.pdb,100,1GYZ.pdb_W1N
9,1GYZ.pdb_W1H,HIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1H,1GYZ.pdb,100,1GYZ.pdb_W1H

## Regardless of their quantity, all wildtype aa_seq are identical to one another.

In [6]:
# check whether aa_seq is unique when mut_type is wt
wt_dataset1 = dataset1.loc[dataset1["mut_type"] == "wt", ["aa_seq", "mut_type"]]
wt_dataset1.groupby(by="aa_seq").describe()

                                                   mut_type
                                                      count unique top freq
aa_seq
ADDEVAKLLVDAYRKNDEDKLEEVKKRYNISDEQVKRLIRKVL               8      1  wt    8
AEEIWQQSVIGDYLARFKNDRVKALKAMEMTWNNMEKKEKLMWIKKAAED        5      1  wt    5
AEIMKKTDFDKVASEYTKIGTISTTGEMSPLDAREDLIKKADEKGAD...        6      1  wt    6
AEKTGIVNVSSSLNAREGASTSSKVIGSLSGNTKVTIVGEEGAFYKI...        5      1  wt    5
AEKTGIVNVSSSLNVREGASTSSKVIGSLSGNTKVTIVGEEGAFYKI...        6      1  wt    6
...                                                     ...    ...  ..  ...
WKVTVKGVEYTFDNPEEAKKFAEELAKKKGGQIHYKDGEFQVH               7      1  wt    7
WVPTKREEKYGVAFYNYDARGADELSLQIGDTVHILETYEGWYRGYT...        6      1  wt    6
YFQGQLNAMAHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI           6      1  wt    6
YKIYPYDSLIVTNSISVKLPKDVDRTRLERHLSPEEFQEVFGMSIEE...        5      1  wt    5
YNLQKLLAPYHKAKTLERQVYELEKLQEKLPEKYKAEYKKKLDQTRV...        6      1  wt    6

[541 rows x 4 columns]

In [7]:
(wt_dataset1.groupby(by="aa_seq").describe().loc[:, "mut_type"].loc[:, "unique"] != 1).sum()

0

# Split Dataset1 and Dataset2

In [8]:
dataset1.loc[:, ["name", "aa_seq", "mut_type", "WT_name", "WT_cluster", "name_original"]].head(10)

,name,aa_seq,mut_type,WT_name,WT_cluster,name_original
0,1GYZ.pdb,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb
1,1GYZ.pdb,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb
2,1GYZ.pdb_wtm,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wtm
3,1GYZ.pdb_wte,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wte
4,1GYZ.pdb_wty,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wty
5,1GYZ.pdb_wth,WIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,wt,1GYZ.pdb,100,1GYZ.pdb_wth
6,1GYZ.pdb_W1Q,QIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1Q,1GYZ.pdb,100,1GYZ.pdb_W1Q
7,1GYZ.pdb_W1E,EIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1E,1GYZ.pdb,100,1GYZ.pdb_W1E
8,1GYZ.pdb_W1N,NIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1N,1GYZ.pdb,100,1GYZ.pdb_W1N
9,1GYZ.pdb_W1H,HIARINAAVRAYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,W1H,1GYZ.pdb,100,1GYZ.pdb_W1H

In [9]:
dataset1.groupby(by="WT_name").describe()

              log10_K50_t                                                    \
                    count      mean       std       min       25%       50%
WT_name
1A0N.pdb           1671.0  1.218565  1.031125 -1.117200  0.433127  1.514479
1A0N.pdb_E24S      1276.0  0.384484  0.794685 -1.092559 -0.373853  0.507823
1A0N.pdb_F20A      1278.0 -0.151943  0.558019 -1.199419 -0.689368 -0.158750
1A0N.pdb_L7S       1276.0  0.040901  0.678488 -1.323021 -0.639580  0.059252
1A0N.pdb_V55A      1276.0  0.252161  0.719199 -1.065931 -0.424712  0.350746
...                   ...       ...       ...       ...       ...       ...
v2_2LXE.pdb        1169.0 -0.363446  0.621196 -1.911123 -0.918767 -0.368539
v2_2M5A.pdb        1232.0  1.309178  0.546818 -0.662189  1.129659  1.487484
v2_4UZX.pdb        1281.0  0.062941  0.584484 -1.303406 -0.424256  0.224931
v2_5XK5.pdb        1544.0  1.124959  0.906164 -1.426060  0.643504  1.568190
v2_6IVS.pdb        1060.0  0.913362  0.572283 -1.620387  0.705562  1.055118

                                  log10_K50_t_95CI_high            ...  \
                    75%       max                 count      mean  ...
WT_name                                                            ...
1A0N.pdb       2.145145  2.690145                1671.0  1.277965  ...
1A0N.pdb_E24S  1.071949  2.034009                1276.0  0.415460  ...
1A0N.pdb_F20A  0.291115  2.037355                1278.0 -0.123457  ...
1A0N.pdb_L7S   0.615592  1.957203                1276.0  0.069012  ...
1A0N.pdb_V55A  0.868576  1.993485                1276.0  0.284223  ...
...                 ...       ...                   ...       ...  ...
v2_2LXE.pdb    0.168472  1.283314                1169.0 -0.298888  ...
v2_2M5A.pdb    1.675549  2.085957                1232.0  1.383533  ...
v2_4UZX.pdb    0.525269  1.279013                1281.0  0.100371  ...
v2_5XK5.pdb    1.811355  2.028957                1544.0  1.148022  ...
v2_6IVS.pdb    1.316987  1.957751                1060.0  0.988077  ...

              deltaG_95CI_low           deltaG_95CI                      \
                          75%       max       count      mean       std
WT_name
1A0N.pdb             4.791939  6.147927      1671.0  0.151870  0.075562
1A0N.pdb_E24S        3.211399  5.445180      1276.0  0.098856  0.039968
1A0N.pdb_F20A        1.853821  5.138652      1278.0  0.111613  0.043756
1A0N.pdb_L7S         2.403055  4.774923      1276.0  0.101984  0.057744
1A0N.pdb_V55A        2.764912  5.009796      1276.0  0.107428  0.044276
...                       ...       ...         ...       ...       ...
v2_2LXE.pdb          2.411730  3.977304      1169.0  0.199930  0.126607
v2_2M5A.pdb          3.561881  4.579767      1232.0  0.200782  0.110574
v2_4UZX.pdb          2.416696  3.791245      1281.0  0.151497  0.081256
v2_5XK5.pdb          5.015822  8.889226      1544.0  0.094045  0.076401
v2_6IVS.pdb          3.857749  4.458777      1060.0  0.201779  0.081568


                    min       25%       50%       75%       max
WT_name
1A0N.pdb       0.036641  0.095816  0.135479  0.188047  0.830135
1A0N.pdb_E24S  0.034119  0.072969  0.089357  0.114180  0.358503
1A0N.pdb_F20A  0.038585  0.082219  0.103149  0.127912  0.413051
1A0N.pdb_L7S   0.034762  0.074542  0.091753  0.117833  1.430733
1A0N.pdb_V55A  0.041055  0.077579  0.097849  0.125561  0.420675
...                 ...       ...       ...       ...       ...
v2_2LXE.pdb    0.049370  0.132797  0.174785  0.234079  1.919842
v2_2M5A.pdb    0.045221  0.128013  0.173785  0.243627  0.917466
v2_4UZX.pdb    0.053874  0.108926  0.139561  0.178172  1.670598
v2_5XK5.pdb    0.030086  0.067616  0.084839  0.107951  2.510767
v2_6IVS.pdb    0.061018  0.143859  0.185899  0.238393  0.731747

[542 rows x 192 columns]

In [10]:
# get all WT_name
WT_name = dataset1.loc[:, "WT_name"].unique()
WT_name.shape

(542,)

## Many columns could be used, now we use `deltaG`
- log10_K50_t
- log10_K50_t_95CI_high
- log10_K50_t_95CI_low
- log10_K50_t_95CI
- fitting_error_t
- log10_K50unfolded_t
- deltaG_t
- deltaG_t_95CI_high
- deltaG_t_95CI_low
- deltaG_t_95CI
- log10_K50_c
- log10_K50_c_95CI_high
- log10_K50_c_95CI_low
- log10_K50_c_95CI
- fitting_error_c
- log10_K50unfolded_c
- deltaG_c
- deltaG_c_95CI_high
- deltaG_c_95CI_low
- deltaG_c_95CI
- `deltaG`
- deltaG_95CI_high
- deltaG_95CI_low
- deltaG_95CI

In [11]:
from pprint import pprint
from tqdm import tqdm
fitness_column = "deltaG"
aa_list = ["A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y"]
all_dict = {}
wt_fitness_dict = {}
wt_seq_dict = {}
for wt_name in tqdm(WT_name):
    all_dict[wt_name] = {}
    # print(wt_name)
    wt_name_df = dataset1.loc[dataset1["WT_name"] == wt_name, ["aa_seq", "mut_type", fitness_column]]
    # for those who wt has different deltaG, use the mean value
    wt_fitness = wt_name_df.loc[wt_name_df["mut_type"] == "wt", fitness_column].mean()
    wt_fitness_dict[wt_name] = wt_fitness
    wt_seq_dict[wt_name] = wt_name_df.loc[wt_name_df["mut_type"] == "wt", "aa_seq"].values[0]
    # print(wt_seq_dict[wt_name])
    # break
    mut_types = wt_name_df.loc[wt_name_df["mut_type"] != "wt", "mut_type"]
    for mut_type in mut_types:
        if len(mut_type.split(":")) > 1:
            continue
        # mut_type_list[-1] should be like A1B
        all_dict[wt_name][mut_type] = wt_name_df.loc[wt_name_df["mut_type"] == mut_type, fitness_column].values.item()

    # break
# pprint(all_dict)

100%|██████████| 542/542 [03:22<00:00,  2.68it/s]

In [12]:
len(all_dict)

542

In [14]:
from collections import defaultdict
mut_dict = {}
for wt, mutations_dict in tqdm(all_dict.items()):
    # print(wt)
    mut_dict[wt] = defaultdict(list)
    for idx, aa in enumerate(wt_seq_dict[wt]):
        mut_dict[wt][f"{aa}{idx+1}"].append((aa, wt_fitness_dict[wt]))
    # print(mut_dict[wt])
    # break
    for mutation in mutations_dict:
        # {"A1": [("B", value), ("C", value)]}
        if mutation[1:-1].isdigit():
            mut_dict[wt][mutation[:-1]].append((mutation[-1], mutations_dict[mutation]))
        elif mutation.startswith("del"):
            mut_dict[wt][mutation[3:]].append(("del", mutations_dict[mutation]))
        elif mutation.startswith("ins"):
            pass # [TODO] don't know how to deal with this
    # print(mut_dict[wt])
    # break

100%|██████████| 542/542 [00:00<00:00, 1115.55it/s]

In [20]:
import pickle as pkl
pkl.dump(mut_dict, open("K50_dG_mut_dict.pkl", "wb"))

In [19]:
import json
for mut in mut_dict:
    json.dump(dict(mut_dict[mut]), open(f"data/{mut}.json", "w"))